services:
  - type: web
    name: vyasa-backend
    runtime: python
    plan: free
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers=2 --timeout=120
    envVars:
      - key: DEBUG
        value: false
      - key: GEMINI_API_KEY
        sync: false # This means Render will prompt you to enter this value
    autoDeploy: true 